Controllers/MarcasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Pasantia.Data;
using Pasantia.Models;
using Microsoft.EntityFrameworkCore;

namespace Pasantia.Controllers
{
    public class MarcasController : Controller
    {
        private ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public MarcasController(ApplicationDbContext context, UserManager<IdentityUser> userManager)


        {
            _context = context;
            _userManager = userManager;
        }

        [Authorize]
        public ActionResult Index(string ErrorEliminar)
        {

            if (ErrorEliminar != null)
            {
                ViewBag.ErrorEliminar = ErrorEliminar;
            }

            return View();
        }

        public JsonResult BuscarTodasMarcas()
        {
            var marcas = _context.Marca.ToList();
            List<MarcaMostrar> marcasMostrar = new List<MarcaMostrar>();
            foreach (var marca in marcas.OrderBy(c => c.MarcaNombre))
            {
                var marcaMostrar = new MarcaMostrar()
                {
                    MarcaID = marca.MarcaID,
                    MarcaNombre = marca.MarcaNombre,
                    Eliminado = marca.Eliminado,
                    //CantidadProductos = marca.Producto.Count
                };
                marcasMostrar.Add(marcaMostrar);
            }

            return Json(marcasMostrar);
        }

        public JsonResult DeshabilitarMarca(int id)
        {
            int resultado = 1;

            Marca marca = _context.Marca.Find(id);

            if (id > 0)
            {
                //VALIDAR SI NO TIENE PRODUCTOS ACTIVOS RELACIONADOS
                var productosActivos = (from o in _context.Producto where o.MarcaID == marca.MarcaID select o).Count();

                if (productosActivos > 0 )
                {
                    //NO SE PUEDE DESHABILITAR LA MARCA.
                    resultado = 0;
                }
                else
                {
                    marca.Eliminado = true;
                    _context.SaveChanges();
                }

            }

            return Json(resultado);
        }

        public ActionResult HabilitarMarca(int id)
        {
            Marca marca = _context.Marca.Find(id);

            marca.Eliminado = false;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public JsonResult GuardarMarca(string MarcaNombre)
        {
            List<string> resultado = new List<string>();

            if (!String.IsNullOrEmpty(MarcaNombre))
            {
                MarcaNombre = MarcaNombre.ToUpper();
                var existeMarca = _context.Marca.Where(x => x.MarcaNombre == MarcaNombre).ToList();

                if (existeMarca.Count > 0)
                {
                    resultado.Add("error_MarcaNombre_existe");
                }
                else
                {
                    Marca marca = new Marca
                    {
                        MarcaNombre = MarcaNombre,
                        Eliminado = false
                    };
                    _context.Marca.Add(marca);
                    _context.SaveChanges();
                    resultado.Add("correcto");
                }

            }
            if (String.IsNullOrEmpty(MarcaNombre)) resultado.Add("error_MarcaNombre");

            return Json(resultado);
        }

        public JsonResult GuardarEditarMarca(int MarcaID, string MarcaNombre)
        {
            //PRIMERO BUSCAMOS EL USUARIO ACTUAL
            var usuarioActual = _userManager.GetUserId(HttpContext.User);
            List<string> resultado = new List<string>();

            if (MarcaID != 0)
            {
                var marca = (from a in _context.Marca where a.MarcaID == MarcaID select a).SingleOrDefault();

                if (marca != null)
                {
                    if (!String.IsNullOrEmpty(MarcaNombre))
                    {
                        MarcaNombre = MarcaNombre.ToUpper();
                        var existeMarca = _context.Marca.Where(x => x.MarcaNombre == MarcaNombre).ToList();

                        if (existeMarca.Count > 0)
                        {
                            resultado.Add("error_MarcaNombre_existe");
                        }
                        else
                        {
                            marca.Eliminado = false;
                            marca.MarcaNombre = MarcaNombre;
                            _context.SaveChanges();
                            resultado.Add("correcto");
                        }
                    }
                    if (String.IsNullOrEmpty(MarcaNombre)) resultado.Add("error_MarcaNombre");
                }
                else
                {
                    resultado.Add("error");
                }
            }

            return Json(resultado);
        }

        public JsonResult BuscarMarca(int MarcaID)
        {
            var resultado = new Marca();

            if (MarcaID != 0)
            {
                Marca marca = _context.Marca.Find(MarcaID);

                resultado.MarcaID = marca.MarcaID;
                resultado.MarcaNombre = marca.MarcaNombre;

            }

            return Json(resultado);
        }

        public JsonResult BuscarMarcasPorDescripcion(string texto)
        {
            List<Marca> marcasMostrar = new List<Marca>();

            if (!string.IsNullOrEmpty(texto))
            {
                texto = texto.ToUpper();
            }

            if (texto.Length > 2)
            {
                var marcasEncontradas = _context.Marca.Where(p => p.MarcaNombre.Contains(texto))
                    .OrderByDescending(p => p.MarcaNombre)
                    .Take(50)
                    .ToList();

                foreach (var marca in marcasEncontradas)
                {
                    var marcaMostrar = new Marca
                    {
                        MarcaID = marca.MarcaID,
                        MarcaNombre = marca.MarcaNombre?.Trim()
                    };
                    marcasMostrar.Add(marcaMostrar);
                }
            }

            return Json(marcasMostrar);
        }
    }
}

Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Pasantia.Data;
using Pasantia.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Globalization;
using Microsoft.EntityFrameworkCore;
using System.Drawing.Printing;
using Microsoft.Data.SqlClient;
using System.Diagnostics;

namespace Pasantia.Controllers
{
    public class ProductosController : Controller
    {
        private ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public ProductosController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [Authorize]
        public ActionResult Index(string ErrorEliminar)
        {
            var productos = _context.Producto.ToList();

            if (ErrorEliminar != null)
            {
                ViewBag.ErrorEliminar = ErrorEliminar;
            }

            //combogralxcondicion

            var marcas = (from m in _context.Marca
              where m.Eliminado == false  // Filtramos las marcas no eliminadas
              select m).ToList();
            marcas.Add(new Marca { MarcaID = 0, MarcaNombre = "[SELECCIONE MARCA]" });
            marcas = marcas.OrderBy(a => a.MarcaNombre).ToList();
            ViewBag.MarcaID = new SelectList(marcas, "MarcaID", "MarcaNombre");

            var categorias = (from c in _context.Categoria
              where c.Eliminado == false  // Filtramos las marcas no eliminadas
              select c).ToList();
            categorias.Add(new Categoria { CategoriaID = 0, CategoriaNombre = "[SELECCIONE CATEGORÍA]" });
            categorias = categorias.OrderBy(a => a.CategoriaNombre).ToList();
            ViewBag.CategoriaID = new SelectList(categorias, "CategoriaID", "CategoriaNombre");

            return View();
        }

        public JsonResult BuscarTodosProductos()
        {
            var productosCargados = (from cam in _context.Producto select cam).ToList();

            List<ProductoMostrar> listaDeProductos = new List<ProductoMostrar>();
            foreach (var p in productosCargados.OrderBy(c => c.Descripcion))
            {
                var marcaNombre = (from c in _context.Marca where c.MarcaID == p.MarcaID select c.MarcaNombre).Single();
                var categoriaNombre = (from c in _context.Categoria where c.CategoriaID == p.CategoriaID select c.CategoriaNombre).Single();

                //VARIABLE DE LA COND DE USADO O REACOND

                var registro = new ProductoMostrar
                {
                    ProductoID = p.ProductoID,
                    Descripcion = p.Descripcion,
                    MarcaNombre = marcaNombre,
                    CategoriaNombre = categoriaNombre
                };
                listaDeProductos.Add(registro);
            }
            return Json(listaDeProductos);
        }

        public JsonResult EliminarProducto(int id)
        {
            Producto producto = _context.Producto.Find(id);
            if (producto != null)
            {
                _context.Producto.Remove(producto);
                _context.SaveChanges();
            }

            var resultado = "Eliminado correctamente.";

            return Json(resultado);
        }


        public JsonResult BuscarProducto(int ProductoID)
        {
            var resultado = new ProductoMostrar();

            if (ProductoID != 0)
            {
                Producto producto = _context.Producto.Find(ProductoID);

                var marcaNombre = (from c in _context.Marca where c.MarcaID == producto.MarcaID select c.MarcaNombre).Single();
                var categoriaNombre = (from c in _context.Categoria where c.CategoriaID == producto.CategoriaID select c.CategoriaNombre).Single();

                resultado.ProductoID = ProductoID;
                resultado.Descripcion = producto.Descripcion;
                resultado.MarcaID = producto.MarcaID;
                resultado.MarcaNombre = marcaNombre;
                resultado.CategoriaID = producto.CategoriaID;
                resultado.CategoriaNombre = categoriaNombre;
            }

            return Json(resultado);
        }

        public JsonResult GuardarProducto(string Descripcion,
            int MarcaID, int CategoriaID)
        {
            List<string> resultado = new List<string>();

            if (!String.IsNullOrEmpty(Descripcion))
            {
                Descripcion = Descripcion.ToUpper();

                //COMPROB DE ESTADO

                //COMPROB DETALLE

                //COMPROB CODIGO

                Producto producto = new Producto
                {
                    Descripcion = Descripcion,
                    MarcaID = MarcaID,
                    CategoriaID = CategoriaID
                };
                _context.Producto.Add(producto);
                _context.SaveChanges();
                resultado.Add("correcto");

            }
            if (String.IsNullOrEmpty(Descripcion)) resultado.Add("error_ProductoNombre");

            return Json(resultado);
        }

        // public JsonResult GuardarProducto(string Descripcion, string Codigo,
        //             int MarcaID, int Estado, string Detalle)
        //         {
        //             List<string> resultado = new List<string>();

        //             if (!String.IsNullOrEmpty(Descripcion))
        //             {
        //                 Descripcion = Descripcion.ToUpper();

        //                 if (Estado < 1 || Estado > 5)
        //                 {
        //                     resultado.Add("error_EstadoFueraDeRango");
        //                     return Json(resultado);
        //                 }

        //                 string detalle = "";
        //                 if (!String.IsNullOrEmpty(Detalle))
        //                 {
        //                     detalle = Detalle.ToUpper();
        //                 }

        //                 string codigoProducto = "";
        //                 if (!String.IsNullOrEmpty(Codigo))
        //                 {
        //                     codigoProducto = Codigo.ToUpper();
        //                 }

        //                 Producto producto = new Producto
        //                 {
        //                     Descripcion = Descripcion,
        //                     MarcaID = MarcaID
        //                 };
        //                 _context.Producto.Add(producto);
        //                 _context.SaveChanges();
        //                 resultado.Add("correcto");

        //             }
        //             if (String.IsNullOrEmpty(Descripcion)) resultado.Add("error_ProductoNombre");

        //             return Json(resultado);
        //         }


        public JsonResult GuardarEditarProducto(int ProductoID, string Descripcion,
            int MarcaID, int CategoriaID)
        {
            //PRIMERO BUSCAMOS EL USUARIO ACTUAL
            var usuarioActual = _userManager.GetUserId(HttpContext.User);
            List<string> resultado = new List<string>();

            if (ProductoID != 0)
            {
                var producto = (from a in _context.Producto where a.ProductoID == ProductoID select a).SingleOrDefault();

                if (producto != null)
                {
                    if (!String.IsNullOrEmpty(Descripcion))
                    {
                        Descripcion = Descripcion.ToUpper();
                    }

                    producto.Descripcion = Descripcion;
                    producto.MarcaID = MarcaID;
                    producto.CategoriaID = CategoriaID;

                    _context.SaveChanges();
                    resultado.Add("correcto");

                    if (String.IsNullOrEmpty(Descripcion)) resultado.Add("error_ProductoNombre");
                }
                else
                {
                    resultado.Add("error");
                }
            }

            return Json(resultado);
        }

        //BUSCAR CATEGORIAS METODO CE RECUPERACION

        // public JsonResult AgregarCategorias(int CategoriaID, int ProductoID)
        // {
        //     bool resultado = false;

        //     //FIJAR INFORMACION DE CULTURA PARA FECHA Y DECIMALES
        //     Thread.CurrentThread.CurrentCulture = new CultureInfo("es-AR");

        //     if (ProductoID != 0)
        //     {
        //         var producto = (from o in _context.Producto where o.ProductoID == ProductoID select o)
        //             .Include(c => c.Categoria).Single();
        //         if (producto != null)
        //         {
        //             if (CategoriaID > 0)
        //             {
        //                 var existeCategoria = _context.Categoria
        //                     .Where(x => x.CategoriaID == CategoriaID).ToList();
        //                 if (existeCategoria.Count > 0)
        //                 {
        //                     resultado = false;
        //                 }
        //                 else
        //                 {
        //                     var categoriaProductos = new ProductoCategoria
        //                     {
        //                         CategoriaID = CategoriaID,
        //                         ProductoID = ProductoID
        //                     };
        //                     _context.SaveChanges();

        //                     resultado = true;
        //                 }

        //             }
        //         }

        //     }

        //     return Json(resultado);
        // }




        // public JsonResult QuitarCategoria(ProductoCategoria)
        // {
        //     bool resultado = false;

        //     if (CategoriaID > 0)
        //     {

Views/Shared/Layout-Login.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aceros Morteros</title>
    <link href="~/css/ClasesLoguin.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light colorNav  box-shadow mb-3  ">
            <div class="container">
                <a class="navbar-brand " asp-area="" asp-controller="Categorias" asp-action="Index"></a>
                <button type="button" onclick="window.location='/'" class="btn btn-outline-light" style="font-weight:bold">VOLVER</button>
                @* <button onclick="window.location='/'" class="cerrarSesion form-inline nav-link">Inicio</button> *@
            </div>
        </nav>
    </header>

    <div class="container body-content mt-5">

        @RenderBody()

    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/sweetalert.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Favicons -->
   <link href="~/img/logo.png" rel="icon">
  <link href="~/img/logo.png" rel="apple-touch-icon">
    <title>@ViewData["Title"] Aceros Morteros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="loguito" src="~/img/logos.png" alt=""></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User.Identity.IsAuthenticated) {
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">CATEGORÍAS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marcas" asp-action="Index">MARCAS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">PRODUCTOS</a>
                        </li>
                    </ul> }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @* <div class="container">
            &copy; 2024 - Pasantía - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div> *@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery-ui.1.12.1.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/sweetalert.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>